############################
## CHANGE THESE
############################

baseURL: "https://hra42.github.io/postrausch.tech"
title: postrausch.tech

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
