############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: About
  url: /about/
  weight: 30
- name: Privacy
  url: /privacy/
  weight: 40
- name: Imprint
  url: /imprint/
  weight: 50